version: "3"

services:
  db:
    image: mongo
    expose:
      - 27017
  jaeger:
    image: jaegertracing/all-in-one:latest
    expose:
      - 14268
      - 16686
    ports:
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  microservice:
    image: akka-http-animal-service:0.1.0-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db
      - JAEGER_HTTP_HOST=jaeger
