apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-collector
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.collectorPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.uiPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.uiNodePort }}
  selector:
    app: {{ .Chart.Name }}
