apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
          env:
            - name: MONGO_URL
              value: "mongodb://default-mongo-mongodb.default.svc.cluster.local:27017"
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
