apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: MONGO_URL
              value: {{ .Values.mongo.url }}
            - name: JAEGER_HTTP_HOST
              value: {{ .Values.jaeger.host }}
            - name: JAEGER_ENABLED
              value: "{{ .Values.jaeger.enabled }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
