apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
